services:
  nginx:
    ports:
      - '${APP_PORT:-8089}:80'

  db:
    platform: linux/amd64
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'

  php-fpm:
    build:
      args:
        - WITH_XDEBUG=${WITH_XDEBUG:-true}
    volumes:
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
