services:
  nginx:
    restart: always
    networks:
      - publish

  php-fpm:
    restart: always

  db:
    restart: always
    environment:
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'

  redis:
    restart: always

networks:
  publish:
    external: true
    name: ${PUBLISH_NETWORK}
