services:
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./docker/nginx/nginx_proxy.conf:/etc/nginx/conf.d/nginx_proxy.conf:ro
            - ./:/var/www/app
        depends_on:
            - php-fpm
        networks:
            - default
        container_name: ${DOCKER_APP_PROXY_CONTAINER_NAME}

    php-fpm:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/app
        command: [ "/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf" ]
        networks:
            - default

    db:
        image: postgres:16
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            LANG: C.UTF-8
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - default
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
            retries: 3
            timeout: 5s

    redis:
        image: redis:alpine
        networks:
            - default
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

volumes:
    db_data:
        name: ${VOLUME_DATABASE_LIB}
        external: true
